-- This file is for use with Corona(R) SDK
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

local M = {}

function M.physicsData(scale)
	local physics = { data =
	{ 
		
		["Frontscene"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 100, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   359, 352.5  ,  569, 83.5  ,  759, -112.5  ,  769, -110.5  ,  772, 352.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 100, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   569, 83.5  ,  499, 132.5  ,  499, 84.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 100, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   638, -71.5  ,  569, 83.5  ,  571, -114.5  ,  637, -113.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 100, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   449, 132.5  ,  359, 352.5  ,  360, 83.5  ,  448, 84.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 100, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   759, -112.5  ,  689, -70.5  ,  689, -113.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 100, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   731, -183.5  ,  759, -112.5  ,  712, -113.5  ,  712, -181.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 100, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   689, -70.5  ,  569, 83.5  ,  638, -71.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 100, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   760, -340.5  ,  759, -112.5  ,  731, -183.5  ,  730, -343.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 100, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   499, 132.5  ,  359, 352.5  ,  449, 132.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 100, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   759, -112.5  ,  569, 83.5  ,  689, -70.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 100, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   569, 83.5  ,  359, 352.5  ,  499, 132.5  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 5, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -750, 72.5  ,  -592, 73.5  ,  -543, 354.5  ,  -752, 354.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 5, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -592, 73.5  ,  -694, 72.5  ,  -695, 35.5  ,  -592, 35.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 5, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -543, 354.5  ,  -592, 73.5  ,  -542, 73.5  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 5, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -75, 122.5  ,  25, 177.5  ,  -129, 351.5  ,  -135, 118.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 5, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -129, 351.5  ,  25, 177.5  ,  72, 176.5  ,  72.66668701171875, 352.88888883590698  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 5, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   25, 177.5  ,  -75, 122.5  ,  -43, 120.5  ,  27, 120.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 5, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -43, 120.5  ,  -75, 122.5  ,  -75, -8.5  ,  -42.611083984375, -6.833343505859375  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 5, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -156, 176.5  ,  -134, 179.5  ,  -129, 351.5  ,  -156, 350.5  }
                    }
                    
                    
                    
		}
		
	} }

        -- apply scale factor
        local s = scale or 1.0
        for bi,body in pairs(physics.data) do
                for fi,fixture in ipairs(body) do
                    if(fixture.shape) then
                        for ci,coordinate in ipairs(fixture.shape) do
                            fixture.shape[ci] = s * coordinate
                        end
                    else
                        fixture.radius = s * fixture.radius
                    end
                end
        end
	
	function physics:get(name)
		return unpack(self.data[name])
	end

	function physics:getFixtureId(name, index)
                return self.data[name][index].pe_fixture_id
	end
	
	return physics;
end

return M

